trigger: 
  branches:
    include:
    - master 
  paths:
    include: 
    - /ci-cd-stages-demo/*

pr:
  paths: 
    include: 
    - /ci-cd-stages-demo/*


variables:
    - name: MajorVersion
      value: 1
    - name: MajorVersion2
      value: $(MajorVersion)
    - name: BuildId
      value: $(Build.BuildId)  #this worked, produced 233
    - name: MinorVersion
      value: 0
    - name: PatchNumber
      value: 999
    - name: RevNumberNoquote
      value: $(Rev:r)  #this produced '$(Rev:r)'
    - name: BuildNameMasterBranch
      value: "${{ variables.MajorVersion }}.${{ variables.MinorVersion}}.${{ variables.PatchNumber }}.${{ variables.BuildId }}"
    - name: BuildNameNonMasterBranch
      value: "${{ variables.MajorVersion }}.${{ variables.MinorVersion}}.${{ variables.PatchNumber }}-prerelease.${{ variables.BuildId }}"
    - name: isMain
      value: ${{ eq(variables['Build.SourceBranch'], 'refs/heads/master') }} #ISMAIN=True when master branch , False othewise
    - name: BuildName
      ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
        value: ${{ variables.BuildNameMasterBranch }}
      ${{else}}:
        value: ${{ variables.BuildNameNonMasterBranch }}




pool:
  vmImage: 'ubuntu-latest'


name: "${{ variables.BUILDNAME }}"

stages:
- stage: BUILD_STAGE
  jobs:
  - job: BUILD_STAGE_JOB
    steps:
    - template: ./devops/build.yml

- stage: DEPLOY_DEV
  dependsOn: BUILD_STAGE
  jobs:
  - job: DEPLOY_DEV_JOB
    steps:
    - template: ./devops/release.yml
      parameters:
        environment: DEV


- stage: DEPLOY_PROD
  dependsOn: DEPLOY_DEV
  condition: eq(variables['build.sourceBranch'], 'refs/heads/master')
  jobs:
  - job: DEPLOY_PROD_JOB
    steps:
    - template: ./devops/release.yml
      parameters:
        environment: UAT
