steps:
- bash: echo "Hello world in build stage"

- task: Bash@3
  displayName: 'Display build number from template'
  inputs:
    targetType: 'inline'
    script: echo '$(Build.BuildNumber)'

- task: Bash@3
  displayName: 'Display variables'
  inputs:
    targetType: 'inline'
    script: set

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: publish
    arguments: '/p:version=$(Build.BuildNumber) --configuration=Release --output $(Pipeline.Workspace)/csharpdemoproject'
    projects: 'ci-cd-stages-demo/src/MyDemoCSharp101/MyDemoConsoleApp1/MyDemoConsoleApp1.csproj'
    zipAfterPublish: false
    modifyOutputPath: false

#Add publish command Pipeline.Workspace
#Create archive
#Publish archive