steps:
- bash: echo "Hello world in build stage"

- task: Bash@3
  displayName: 'Display build number from template'
  inputs:
    targetType: 'inline'
    script: echo '$(Build.BuildNumber)'

- task: Bash@3
  displayName: 'Display variables'
  inputs:
    targetType: 'inline'
    script: set

