
- task: Bash@3
  displayName: 'Display build number from template'
  inputs:
    targetType: 'inline'
    script: echo '$(Build.BuildNumber)'

- task: Bash@3
  displayName: 'Display variables'
  inputs:
    targetType: 'inline'
    script: set

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9' # string. Required. Version spec. Default: 3.x.
    #disableDownloadFromRegistry: false # boolean. Disable downloading releases from the GitHub registry. Default: false.
    #allowUnstable: false # boolean. Optional. Use when disableDownloadFromRegistry = false. Allow downloading unstable releases. Default: false.
    #githubToken: # string. Optional. Use when disableDownloadFromRegistry = false. GitHub token for GitHub Actions python registry. 
    #addToPath: true # boolean. Add to PATH. Default: true.
  # Advanced
    architecture: 'x64' # 'x86' | 'x64'. Required. Architecture. Default: x64.


- powershell: |
   Write-Host "Displaying Python version"
   python --version
   python -m venv myenv
   Write-Host "Activating environment"
   myenv/Scripts/Activate.ps1
   Write-Host "Activated environment"
   pip install pytest
   pip install -r requirements.txt
   pytest
  displayName: 'Run python tests'

- task: Bash@3
  displayName: 'Display variables'
  inputs:
    targetType: 'inline'
    script: set
